{{ config(materialized='table') }}
with source_data as (
    select PROVINCE,sum(POPULATION) as TOTAL_POPULATION,SUM(TOTAL_DISTRICTS) as TOTAL_DISTRICTS,SUM(TOTAL_CITIES) as TOTAL_CITIES,SUM(TOTAL_CASES) as TOTAL_CASES, SUM(TOTAL_DEATHS) as TOTAL_DEATHS, avg(CASE_FATALITY_RATE) as AVG_FATALITY_RATE, avg(GROWTH_FACTOR_OF_NEW_DEATHS) as AVG_GROWTH_FACTOR_OF_NEW_DEATHS,sum(TOTAL_DEATHS_PER_MILLION) as TOTAL_DEATHS_PER_MILLION 
    from {{ ref('COVID19_INDONESIA') }}
    group by PROVINCE
)
select * from source_data
