{{ config(materialized='table') }}
with source_data as (
    select month_col,SUM(TOTAL_CASES) as TOTAL_CASES,SUM(TOTAL_ACTIVE_CASES) as TOTAL_ACTIVE_CASES,SUM(NEW_CASES) as TOTAL_NEW_CASES,SUM(TOTAL_RECOVERED) as TOTAL_RECOVERED,SUM(TOTAL_DEATHS) as TOTAL_DEATHS,avg(CASE_FATALITY_RATE) as AVG_FATALITY_RATE, avg(GROWTH_FACTOR_OF_NEW_DEATHS) as AVG_GROWTH_FACTOR_OF_NEW_DEATHS,sum(TOTAL_DEATHS_PER_MILLION) as TOTAL_DEATHS_PER_MILLION 
    from {{ ref('COVID19_INDONESIA') }}
    group by month_col
)
select * from source_data
