{{ config(materialized='table') }}

with source_data as (

    select PROVINCE,sum(POPULATION),SUM(TOTAL_DISTRICTS),SUM(TOTAL_CITIES),SUM(TOTAL_CASES),SUM(TOTAL_ACTIVE_CASES),SUM(TOTAL_RECOVERED),SUM(TOTAL_DEATHS) from "FIVETRAN_INTERVIEW_DB"."GOOGLE_SHEETS"."COVID_19_INDONESIA_MAHILAESHWAR_M"
    group by PROVINCE
    

)

select *
from source_data
